### ISSUE TITLE
Styling für Slack errnie hinzufügen

### ISSUE THREAD

**Issue by BjoernSchotte** [mayflower/err-atlassian#1]
Siehe Screenshot.

Wäre toll, wenn der errnie ein Styling hätte wie die Jira-Slack-Integration - dann würde ich umschwenken für die Channels, in denen wir das nutzen.

<img width="508" alt="errnie-vs-bert" src="https://cloud.githubusercontent.com/assets/870033/18906181/c5842ecc-8566-11e6-9fbe-513716b54133.png">

**Comment by phryneas** [comment]
könnte über Slack-Markdown recht gut so machbar sein, dass es im Jabber auch noch gut aussieht - siehe https://get.slack.help/hc/en-us/articles/202288908-Format-your-messages

obige Ausgabe wäre also mit Blockquotes (einfach einmal >>> bevor der Tickettext kommt) schon deutlich hübscher:

```
[jira][CRM-16404 - mydays: Symfony Website] Lenz Weber created a comment: 
>>> Errnie, noch ein Test.
https://jira.mayflower.de/browse/CRM-16404?focusedCommentId=78148&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-78148
```

wenn man Links als Wörter anzeigen wollen würde, müsste man da über die Message-Formatting-API gehen - inwiefern das mit Errbox klappt weiß ich nicht.
https://api.slack.com/docs/message-formatting

**Comment by phryneas** [comment]
Links _könnten_ mit <url|text> klappen, je nachdem wie die API genutzt wird.
Also dann

```
[jira]<https://jira.mayflower.de/browse/CRM-16404?focusedCommentId=78148&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-78148|[CRM-16404 - mydays: Symfony Website]> Lenz Weber created a comment: 
>>> Errnie, noch ein Test.
```
