### ISSUE TITLE
Show less Link einfügen

### ISSUE THREAD

**Issue by BjoernSchotte** [mayflower/err-atlassian#5]
Aktuell wird ein "Show more ..." link bei zB Issue Creation angezeigt, um den kompletten Inhalt des angelegten Tickets lesen zu können.

Wenn ich via "Show more ..." expande, habe ich keine Möglichkeit mehr, das zu closen, weil ein "Show less" link dann fehlt.
<img width="379" alt="showmore" src="https://cloud.githubusercontent.com/assets/870033/22780430/02e469e6-eebf-11e6-8bf4-e08f8c9fdf11.png">
<img width="454" alt="showlessmissing" src="https://cloud.githubusercontent.com/assets/870033/22780431/04e9cede-eebf-11e6-961c-9383ff8e9170.png">

**Comment by fpletz** [comment]
Das ist eher ein Problem von Slack und nicht von diesem Plugin. Geht das bei anderen Cards?

**Comment by BjoernSchotte** [comment]
Ich habe diesbezüglich noch keine anderen Cards gesehen. Wo kann ich eine solche Card provozieren? Dann könnte ich mir das anschauen.

**Comment by BjoernSchotte** [comment]
Habe mal ein wenig in den Slack Helpfiles recherchiert. Das lässt sich tatsächlich nicht beeinflussen.

Ich habe eine andere Idee: nicht einfach plain die Description des Tickets as-is dumpen, sondern über einen HTML Container selbst ein "Show more / show less" generieren, das dann den DOM auf- bzw. zuklappt.

**Comment by globin** [comment]
Man kann kein HTML o.ä. einfügen, kann Slack halt nicht 🤷‍♂️
